### PR TITLE
Silice FireV

### PR DESCRIPTION
**Pull request by sylefeb**
This is adding the FireV CPU which is written in Silice and described in details here: https://github.com/sylefeb/Silice/blob/draft/projects/fire-v/doc/fire-v.md

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @sylefeb! This is merged and I'll play a bit with it.

**Comment by enjoy-digital** [comment]
I've been able to run it in simulation and did minor changes with https://github.com/enjoy-digital/litex/commit/87d5d7c87ca0f956c01950328bc86775bd348fb8.

**Comment by mithro** [comment]
Awesome to see a Silice CPU in LiteX!

**Comment by sylefeb** [comment]
It is!! I'm looking forward to keep exploring how Silice can interface with Litex.

**Pull request merged**
