### PR TITLE
litex_sim now working on MacOS and Linux

### PR DESCRIPTION
**Pull request by BracketMaster**
I modified the makefiles so that litex_sim works on MacOS.
The main issues were 

1. ``-Werror`` - this is not a supported option in clang
2. ``-Wl`` and ``-soname``. These features are not supported by the MACHO linker format.

I check if uname is Darwin and then change the compiler flags, otherwise, the flags remain untouched for Linux.

I also updated the instruction in the README to include MacOS.

Lastly, I added a nice screenshot of the LiteX Bios to the end of the README.

I have verified that the current changes work in both MacOS and Linux by doing ``litex_sim``.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @BracketMaster! Happy to merge it but i have a preference for a Linux screenshot since that's the recommended platform. Can you rebase your pull request with all your changes except the screenshot and integrate the one attached instead? 

litex_prompt

Thanks.

**Comment by BracketMaster** [comment]
Sure thing.

Linux is the recommended platform?
Where's the love for us BSD people? :)

**Comment by enjoy-digital** [comment]
Thanks for the update. Would you mind rebasing the PR to only have 1 commit? (that's just to avoid having the old screenshot to be included in the git history and enlarging the repository for nothing).

**Comment by BracketMaster** [comment]
Oh yes sorry

**Comment by BracketMaster** [comment]
rebased and forced.
Try now.

**Comment by enjoy-digital** [comment]
Thanks, merged.

**Pull request merged**
