### PR TITLE
SVD export

### PR DESCRIPTION
**Pull request by Disasm**
SVD format is used among different ARM microcontrollers for describing the chip peripherals.
Peripheral descriptions in this format can also be used to generate Rust bindings with [svd2rust](https://github.com/rust-embedded/svd2rust/).

### CODE REVIEW

**Comment by mithro** [comment]
PTAL - @xobs

**Comment by xobs** [comment]
This is possible with lxsocdoc (https://github.com/litex-hub/lxsocdoc).  This project needs to get integrated into litex.

**Comment by xobs** [comment]
Note that with those SVD files, registers are completely documented, and as a result we get autogenerated Rust documents that look like: https://docs.rs/fomu-pac/0.0.3/fomu_pac/

**Comment by Disasm** [comment]
Oh, indeed, thank you for pointing out!

**Pull request closed without merging**
