### PR TITLE
Rommable linker files and startup

### PR DESCRIPTION
**Pull request by mubes**
Not sure if this is useful, but its not something I found already....feel free to bounce it if it's not something you need, but this adds rommable code boot for vexriscv.  For any individual project folks will need to edit this file to their needs, but at least it's a working starting point (it's used in tinyuf2, for example).

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @mubes, this is indeed useful, but i'm not sure we should include it directly in LiteX (it will be difficult to maintain and if we add it, then users will also want to have it for the others CPU and for the others configurations :)). Maybe we could add a page in the Wiki explaining how to run the CPU code from ROM with a link to a useful crt0/linker for that?

**Comment by mubes** [comment]
Hiya, I think that would be fine provided we put a comment in the 'regular' linker file pointing people to the rommable version.  It is however a bit unusual to not have rommable boot up code directly available in the SDK for an embedded system, most programmers would expect to find ram-run and rom-run ld and startup directly available.  

It looks like this is already partially recognised in #145 ... give me a little while and I'll see if I can align this with that, then it would just be or1k and minerva that are missing it.

**Comment by enjoy-digital** [comment]
@mubes:  we can indeed improve the situation but we should make sure to avoid as much as duplication as possible and if supported try to make it available to all CPUs. We also need to add a test or/and describe how to test it for maintenance. If support is added to one CPU with a test or instruction to test, i could add support for the others CPUs.

**Comment by mubes** [comment]
OK, I just pushed a small update to align this with the other CPUs that already have `EXECUTE_IN_PLACE` support. That's allowed unification of the crt, but a separate ld file is still needed to put the sections into rom.

I have tested this in tinyUF2 and its fine but I don't really know how to slot a test case into litex for this because it needs a whole build that is tested on a CPU.  The actual code for testing is straightforward;

```#include <stdio.h>

uint32_t tv=42;

void main(void)

{
  if (42!=tv)
    {
      printf("Initialisation of data segment failed\n");
      return;
    }

  tv = 16;
  if (16!=tv)
    {
      printf("Cannot write to data segment\n");
      return;
    }

  printf("Data test passed\n");
}
```
...but I'm not sure how to incorporate it into the existing framework?
DAVE

**Comment by enjoy-digital** [comment]
@mubes: sorry i'm not sure i understood correctly the issue in your initial post. This is now fixed by https://github.com/enjoy-digital/litex/issues/566 and copy of data section is included in the crt0 of all CPUs.

**Pull request closed without merging**
