### PR TITLE
Add platform definitions for fomu variants

### PR DESCRIPTION
**Pull request by TomKeddie**
Details about fomu can be found at https://github.com/im-tomu/fomu-hardware and https://www.crowdsupply.com/sutajio-kosagi/fomu

Was reviewed earlier by @mithro and @xobs please seek their input as needed (https://github.com/TomKeddie/litex/pull/1)

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks for the Fomu platforms definitions! To ease supporting more boards and define level of support for all boards, i created https://github.com/litex-hub/litex-boards. This is now the place where we'll put the boards definitions. (some platforms/boards will still be in litex main repository, but that's the ones that are use for the development/CI). Can you create a pull request on this repository and put the platforms definition to put the fomu boards definition in the partner directory?

**Comment by TomKeddie** [comment]
Will do.

**Comment by enjoy-digital** [comment]
Thanks.

**Comment by TomKeddie** [comment]
@enjoy-digital I'm not sure if fomu is consider community, official or partner?  Thanks.

**Comment by enjoy-digital** [comment]
partner is fine for fomu.

**Comment by mithro** [comment]
@TomKeddie I would definitely say partner.

**Comment by TomKeddie** [comment]
Replaced by https://github.com/litex-hub/litex-boards/pull/1

**Pull request closed without merging**
