### PR TITLE
Some small changes to liblitedram

### PR DESCRIPTION
**Pull request by Icenowy**
This PR covers some small fixes to liblitedram, one about using the longest 1 for read-leveling, one about scale up values in clk/cmd delay calibration, and the last about an off-by-1 error when write leveling.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @Icenowy, I'll review it carefully and will do some tests on different hardware before merging. Can you specify on which board this has been tested?

**Comment by Icenowy** [comment]
I am testing this on Sitlinv STLV7325.

**Comment by Icenowy** [comment]
Also tested on iSX iM1283 and it works.

**Comment by enjoy-digital** [comment]
Thanks @Icenowy, this looks good and I've been able to test it on various configuration (Artix7/DDR3, Kintex7/DDR3, Ultrascale/DDR4, ECP5/DDR3), so we can merge.

**Pull request merged**
