### PR TITLE
WIP - BIOS: Flashboot without main ram

### PR DESCRIPTION
**Pull request by rohitk-singh**
Modified flashboot() to skip copy to main ram if there is no main
ram, and instead execute in place out of SPI flash.  (For this to
work the linker .ld will also need to redirect references to be
inside the SPI flash mapping.)

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Isn't it a duplicate of #55?

**Comment by mithro** [comment]
@enjoy-digital - @rohitk-singh Is testing this change on the cmod-a7

**Comment by enjoy-digital** [comment]
ok, we'll merge it once validated.

**Comment by enjoy-digital** [comment]
@rohitk-singh: Was it validated?

**Comment by rohitk-singh** [comment]
@enjoy-digital No. We ran issues with Cmod A7 and were not able to program it. Most likely issues with Openocd and the 12MHz clock sourced from FTDI, which openocd controls. I'll test it with MimasV2 and then confirm. Please do not merge yet.

**Comment by enjoy-digital** [comment]
@rohitk-singh: any update?

**Comment by rohitk-singh** [comment]
@enjoy-digital Sorry for delay. I just tested it. Works fine. Designer just has to make **sure** to define 'flash_boot_address` in the Python SoC target class with the correct memory-mapped location of the firmware to boot in SPI Flash. Other wise BIOS will not support flash boot.

**Comment by enjoy-digital** [comment]
thanks! merged.

**Pull request merged**
