### PR TITLE
Remove -flto flag from demo.bin

### PR DESCRIPTION
**Pull request by developandplay**
Fixes the failing lift-off on the Rocket chip.

### CODE REVIEW

**Comment by mithro** [comment]
@developandplay - Can you upload the `demo.bin` (or even better the original `demo.elf` file) compiled with `-flto` and without `-flto`?

We should really figure out why `-flto` is breaking the demo on Rocket.

@kgugala - Do you have someone who could dive into this and figure out what is going on?

**Comment by kgugala** [comment]
@mithro I'll find someone to check this.
@developandplay it'll be helpful if you can share the binaries

**Comment by developandplay** [comment]
Sure here are the binaries and a default dump. I had a quick look at it but I couldn't make anything of the binary differences as there seem to be quite a lot of them.

[demo-binaries.zip](https://github.com/enjoy-digital/litex/files/8400004/demo-binaries.zip)

**Comment by developandplay** [comment]
I just tried running the same thing on BlackParrot in simulation. (With `ram_boot_offset  = 0x80000000`)
```
lxsim --cpu-type blackparrot --cpu-variant standard --with-sdram   # for csr.csv generation
litex_bare_metal_demo --build-path=build/sim
lxsim --cpu-type blackparrot --cpu-variant standard --with-sdram --sdram-init demo.bin
```

The outcome is also that it works without `-flto` but fails with `-flto`.
So it seems like it's more a binary issue than a Rocket issue.

**Comment by mithro** [comment]
@developandplay - It is most certainly an issue with the binary in some way. 

`-flto` enables "link time optimization" (https://gcc.gnu.org/wiki/LinkTimeOptimization) which is primarily suppose to remove unused code sections resulting is much smaller firmware sizes (as only used functionality is actually included).

**Comment by enjoy-digital** [comment]
LTO has been disabled in the BIOS since still need to cause random issue and #682 has been re-opened (see https://github.com/enjoy-digital/litex/issues/682#issuecomment-1145927034). I'm closing this since no longer useful but it would still be interesting to properly investigate LTO issues to be able to enable it.

**Pull request closed without merging**
