### PR TITLE
Dts schema compliance

### LINKED ISSUE #1905: Generated DTS lacks root compatible and model properties
According to the Devicetree Specification, the "model" and "compatible" properties are mandatory for the root node.
However, litex/tools/litex_json2dts_linux.py does not generate them.

This may lead to subtle issues, cfr.
https://lore.kernel.org/all/CAMuHMdUKa-KdWfYswEpFvj3RjQPM+ThhU85myfBGVkXxZqbHWw@mail.gmail.com

### PR DESCRIPTION
**Pull request by AndrewD**
This fixes several linux schema validation issues. Closes #1905, see #1960

This branch is on top of the branch for #1972 but that is not a dependency.

### CODE REVIEW

**Review by enjoy-digital — APPROVED** [review]
Thanks @AndrewD, this looks fine. I'll do at least a minor adjustment (move adding the identifier constant to add_identifier method) and we'll also test the updated generated .dts on the LiteX HW CI.

**Comment by enjoy-digital** [comment]
This is merged with two minor modifications on top of it:
- https://github.com/enjoy-digital/litex/commit/72854b8bef3af6899d4cc1a2e2786f573b32a15c
- https://github.com/enjoy-digital/litex/commit/cc1a37e3866378c975a4cb644846a178a1d6cdca

Thanks!

**Comment by AndrewD** [comment]
@enjoy-digital with the change in [cc1a37e](https://github.com/enjoy-digital/litex/commit/cc1a37e3866378c975a4cb644846a178a1d6cdca) this line probably needs to change to platform_name too: [litex_json2dts_linux.py#L58](https://github.com/enjoy-digital/litex/blob/b31114bd50c227e5a0c0ca6c607641db4c19304a/litex/tools/litex_json2dts_linux.py#L58)

Related to #1960

**Comment by AndrewD** [comment]
>  we'll also test the updated generated .dts on the LiteX HW CI.

The ci failure is because I used a python 3.10 feature in the type hints. Can we bump the minimum python version, or is there a desire to maintain support for 3.9?

**Comment by enjoy-digital** [comment]
If possible, it would be nice to not use python 3.10 specific features for now. We could bump the requirement, but that's maybe not the right time.

**Comment by AndrewD** [comment]
> If possible, it would be nice to not use python 3.10 specific features for now. We could bump the requirement, but that's maybe not the right time.

Would pushing a rebase that addresses this help? It looks minor.

**Comment by enjoy-digital** [comment]
If you can just provide the change, I could integrate.

**Pull request merged**
