### PR TITLE
trellis: Pass speed argument to nextpnr

### PR DESCRIPTION
**Pull request by kbeckmann**
Excuse me for the hacky parsing in nextpnr_ecp5_speed(). If you have a better idea feel free to adjust :).

### CODE REVIEW

**Comment by kbeckmann** [comment]
> This would be "speed grade" I think?

That's right. I changed the commit to call the variables speed_grade. The flag to nextpnr is just `--speed`.

**Comment by enjoy-digital** [comment]
Thanks @kbeckmann! It's merged and slightly modified to avoid having the speed_grade included in the package after the split("-"): i just regrouped the parsing in a single function with: https://github.com/enjoy-digital/litex/commit/83ad674feb21098c0e51e2d1c70dbdffb1744cd5

**Comment by kbeckmann** [comment]
Nice, thanks for the pull and cleanup!

**Comment by enjoy-digital** [comment]
For info, this allow removing the workaround i saw yesterday on the Hackaday badge when merging: https://github.com/litex-hub/litex-boards/commit/82601ff7004fbef5dd6ddb593ff28392c8beaf90

**Pull request merged**
