### PR TITLE
Zynq7000 litex_server OpenOCD JTAG fixes

### PR DESCRIPTION
**Pull request by FlyGoat**
Hi all,

This PR fixes some issues preventing litex_server being connected to Zynq 7000 series JTAG.

Here is the working log now:
```
(.venv) ➜  rv litex_server --jtag-config /usr/share/openocd/scripts/board/digilent_zedboard.cfg --jtag 
Open On-Chip Debugger 0.12.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
zynqpl_program
jtagstream_serve
Info : clock speed 1000 kHz
Info : JTAG tap: zynq_pl.bs tap/device found: 0x23727093 (mfg: 0x049 (Xilinx), part: 0x3727, ver: 0x2)
Info : JTAG tap: zynq.cpu tap/device found: 0x4ba00477 (mfg: 0x23b (ARM Ltd), part: 0xba00, ver: 0x4)
Info : zynq.cpu0: hardware has 6 breakpoints, 4 watchpoints
Info : zynq.cpu1: hardware has 6 breakpoints, 4 watchpoints
Info : starting gdb server for zynq.cpu0 on 3333
Info : Listening on port 3333 for gdb connections
[CommUART] port: JTAG / tcp port: 1234
```

Please review.

Thanks

### CODE REVIEW

**Comment by trabucayre** [comment]
It's LGTM. But I have tried `litex_cli --regs` and it fails.
Ok I have used an arty z7 but it's the same principle (jtag interface must be changed).

Could you provides informations about tests/setup ?
Thanks

**Comment by FlyGoat** [comment]
@trabucayre So I'm on ZedBoard as well, here's my setup:

Firstly, I had to patch target file to allow UART to be inserted
```
diff --git a/litex_boards/targets/digilent_zedboard.py b/litex_boards/targets/digilent_zedboard.py
index 206e56c..e003ba4 100755
--- a/litex_boards/targets/digilent_zedboard.py
+++ b/litex_boards/targets/digilent_zedboard.py
@@ -55,6 +55,9 @@ class BaseSoC(SoCCore):
     def __init__(self, sys_clk_freq=100e6, with_led_chaser=True, **kwargs):
         platform = digilent_zedboard.Platform()
 
+        kwargs["uart_name"]     = "crossover"
+        kwargs["with_jtagbone"] = True
+
         # CRG --------------------------------------------------------------------------------------
         use_ps7_clk = (kwargs.get("cpu_type", None) == "zynq7000")
         self.crg = _CRG(platform, sys_clk_freq, use_ps7_clk)
@@ -149,7 +152,6 @@ def main():
     parser = LiteXArgumentParser(platform=digilent_zedboard.Platform, description="LiteX SoC on Zedboard.")
     parser.add_target_argument("--sys-clk-freq", default=100e6, type=float, help="System clock frequency.")
     parser.set_defaults(cpu_type="zynq7000")
-    parser.set_defaults(no_uart=True)
     args = parser.parse_args()
 
     soc = BaseSoC(
```

Then I built bitstream with:

```
python3 -m litex_boards.targets.digilent_zedboard --cpu-type=vexriscv --build --with-jtagbone  --uart-name crossover --csr-csv csr.csv
```

I had to load the generated bitstream manually with Vivado, as there are some problems with OpenOCD loader, I'm working on a patch.

After bitstream get loaded, I ran
```
litex_server --jtag-config /usr/share/openocd/scripts/board/digilent_zedboard.cfg --jtag
```
To start litex_server, which gives me:
```
(.venv) ➜  rv litex_server --jtag-config /usr/share/openocd/scripts/board/digilent_zedboard.cfg --jtag 
Open On-Chip Debugger 0.12.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
zynqpl_program
jtagstream_serve
Info : clock speed 1000 kHz
Info : JTAG tap: zynq_pl.bs tap/device found: 0x23727093 (mfg: 0x049 (Xilinx), part: 0x3727, ver: 0x2)
Info : JTAG tap: zynq.cpu tap/device found: 0x4ba00477 (mfg: 0x23b (ARM Ltd), part: 0xba00, ver: 0x4)
Info : zynq.cpu0: hardware has 6 breakpoints, 4 watchpoints
Info : zynq.cpu1: hardware has 6 breakpoints, 4 watchpoints
Info : starting gdb server for zynq.cpu0 on 3333
Info : Listening on port 3333 for gdb connections
[CommUART] port: JTAG / tcp port: 1234
Connected with 127.0.0.1:44752
Disconnect
Connected with 127.0.0.1:53576
Disconnect
```

And then I can confirm `litex_cli` is working:
```
(.venv) ➜  rv litex_cli --ident                                                                        
LiteX SoC on Zedboard 2024-03-05 21:18:37
(.venv) ➜  rv litex_cli --regs 
0xf0000000 : 0x00000000 ctrl_reset
0xf0000004 : 0x12345678 ctrl_scratch
0xf0000008 : 0x00000000 ctrl_bus_errors
0xf0001000 : 0x00000000 leds_out
0xf0001800 : 0x00000000 timer0_load
0xf0001804 : 0x00000000 timer0_reload
0xf0001808 : 0x00000000 timer0_en
0xf000180c : 0x00000000 timer0_update_value
0xf0001810 : 0x00000000 timer0_value
0xf0001814 : 0x00000001 timer0_ev_status
0xf0001818 : 0x00000001 timer0_ev_pending
0xf000181c : 0x00000000 timer0_ev_enable
0xf0002000 : 0x00000000 uart_rxtx
0xf0002004 : 0x00000001 uart_txfull
0xf0002008 : 0x00000001 uart_rxempty
0xf000200c : 0x00000000 uart_ev_status
0xf0002010 : 0x00000000 uart_ev_pending
0xf0002014 : 0x00000003 uart_ev_enable
0xf0002018 : 0x00000000 uart_txempty
0xf000201c : 0x00000000 uart_rxfull
0xf0002020 : 0x0000000d uart_xover_rxtx
0xf0002024 : 0x00000000 uart_xover_txfull
0xf0002028 : 0x00000000 uart_xover_rxempty
0xf000202c : 0x00000003 uart_xover_ev_status
0xf0002030 : 0x00000003 uart_xover_ev_pending
0xf0002034 : 0x00000000 uart_xover_ev_enable
0xf0002038 : 0x00000001 uart_xover_txempty
0xf000203c : 0x00000001 uart_xover_rxfull
```

**Comment by FlyGoat** [comment]
Ok I sorted out bitfile loading issue with latest commit.

**Comment by trabucayre** [comment]
Ok. Now it's works for me (in fact all target's modifications aren't required).
With crossover I'm also able to have (a slow) console access.

**Comment by FlyGoat** [comment]
> Ok. Now it's works for me (in fact all target's modifications aren't required). With crossover I'm also able to have (a slow) console access.

How can I insert crossover uart with `no_uart` being default?

**Comment by trabucayre** [comment]
`kwargs` modifications aren't required, but it's true the `no_uart` is a problem. Maybe a more clever approach is needed. Someting like:
```
kwargs["no_uart"] = cpu_type == "zynq7000" or uart_name != "crossover"
````
at *BaseSoC* level and removing `set_default`

**Comment by trabucayre** [comment]
Applied. Thanks @FlyGoat !

**Comment by trabucayre** [comment]
I have reverted [commit](https://github.com/enjoy-digital/litex/commit/a7d441488c784859813579321581c80dc7fc10ba). In fact it's not required (see [this](https://github.com/enjoy-digital/litex/blob/master/litex/build/generic_programmer.py#L65)).

**Comment by enjoy-digital** [comment]
Thanks @FlyGoat and @trabucayre, this will be very useful for project like https://github.com/360nosc0pe/scope and similar Zynq based hardware.

**Comment by FlyGoat** [comment]
> `kwargs` modifications aren't required, but it's true the `no_uart` is a problem. Maybe a more clever approach is needed. Someting like:
> 
> ```
> kwargs["no_uart"] = cpu_type == "zynq7000" or uart_name != "crossover"
> ```
> 
> at _BaseSoC_ level and removing `set_default`

Hi @trabucayre do you want to make this change to zynq targets universally in `litex-boards`?

**Pull request merged**
