### PR TITLE
Add i2c master

### PR DESCRIPTION
**Pull request by AndrewD**
This PR imports the I2CMaster from misoc and adapts it to Litex.

It also includes the history of the various fixes that were required to make it actually work for READ: it appeared from our testing that while read was implemented it had never been used...

This core has limitations but it works and is far better than bitbang.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @AndrewD, @rtucker85, this is merged. I'll do some test with it soon.

**Comment by AndrewD** [comment]
@enjoy-digital I have a python app that can do an i2c scan over etherbone: maybe we can add this to litex in some form?

**Comment by AndrewD** [comment]
@enjoy-digital thanks for merging so quickly 👍

**Comment by enjoy-digital** [comment]
@AndrewD: The I2C scan script over Etherbone could be interesting yes. We could maybe integrate it to litex_cli, but you can just provide the script and I will eventually update/rework the integration while testing.

**Pull request merged**
