### PR TITLE
Add multiple Python versions, Windows and Mac to Travis CI testing

### PR DESCRIPTION
**Pull request by mithro**
This tests that the tooling also works on Mac and Windows.

Needs #452 to be merged first.

### CODE REVIEW

**Comment by mithro** [comment]
@enjoy-digital  -- I'm a bit confused about how the build at https://travis-ci.com/github/enjoy-digital/litex/jobs/315546886 succeeded, given it downloaded a Linux binary on Mac? Is the compiler never actually used as part of the `setup.py test` command?

**Comment by enjoy-digital** [comment]
@mithro: Thanks for the work, the current travis CI focus on testing LiteX itself and not really the installation on various OSes. Could it be something tested in `litex-buildenv` so that i can still use the minimal `travis.yml` i set up for my needs?

**Comment by mithro** [comment]
@enjoy-digital LiteX-BuildEnv doesn't currently support Mac / Windows. Hopefully when I finish debugging it should be only a fairly small change to your existing Travis file.

**Comment by mithro** [comment]
@enjoy-digital - Take a look at this CL now. It seems like it turned out reasonably simple?

**Comment by mithro** [comment]
@enjoy-digital - This pull request has shown that [litex is currently broken on Python 3.5](https://travis-ci.com/github/enjoy-digital/litex/jobs/315692914) -- should we fix that or just drop support for Python 3.5?

**Comment by mithro** [comment]
(The issue seems to be the use of f-strings which are not supported by Python 3.5)

**Comment by enjoy-digital** [comment]
@mithro: thanks, i just deprecated Python3.5 support with https://github.com/enjoy-digital/litex/commit/30d25ffe5b2481368de3dad2f6d4dbf8b08b0f63. I'm going to merge your PR and do the adaptation to remove Python3.5 test.

**Pull request merged**
