### PR TITLE
soc/software/litesdcard: update for response register back to 128 bits

### PR DESCRIPTION
**Pull request by gsomlo**
The additional (17th) byte returned via the response register was ignored by software (bios and kernel), so LiteSDCard was updated to only return the (original, useful) 128 bits.

This patch updates the LiteSDCard code in the LiteX bios to only expect those 128 bits, and to do so in a manner that's portable across CSR data widths and alignments.

NOTES:
1. Depends on https://github.com/enjoy-digital/litesdcard/pull/13
2. Tested on nexys4ddr with `(mor1kx, vexriscv, rocket) x (csr_data_with \in {8, 32})`
3. Side-steps issue #546 (which I'd still like us to agree upon one way or another, but is no longer "urgent" :))

### CODE REVIEW

**Comment by gsomlo** [comment]
@mateusz-holenko  @kamilrakoczy please also take a look and let us know what you think!

**Comment by gsomlo** [comment]
@enjoy-digital I just want to drop this here so I don't forget. Regardless of whether we can stuff the sdcard response register back into 4 (instead of 4.25) bytes (and I'm fairly confident we can, based on successful tests), we should define a packed struct (or union overlaid on top of `u32_t sdcard_response[4]`) with named fields, to avoid doing stuff like e.g. this:
https://github.com/enjoy-digital/litex/blob/master/litex/soc/software/liblitesdcard/sdcard.c#L549
in the long term. I can volunteer to clean that up, but want to see this PR resolved first :)

**Comment by enjoy-digital** [comment]
Thanks, i'm merging and will have a closer look at the others points. @gsomlo: once things are clear in the gateware side, happy to have your help to clean that up on the software side.

**Comment by mateusz-holenko** [comment]
@gsomlo This simplifies code a lot and looks good.

**Pull request merged**
