### PR TITLE
Replace libbase with picolibc

### PR DESCRIPTION
**Pull request by michalsieron**
### _litex_setup.py_

Added pythondata-software-picolibc to downloaded repositories. It contains picolibc repo as its submodule, so when installing it should get newest picolibc.

### _software/libc_

There is a new directory litex/soc/software/libc, which contains stuff needed for picolibc to compile and work:

#### _Makefile_

Outside of running meson commands for picolibc compilation, it also creates cross.txt file, which is necessary for meson config.

#### _\<cpu\>/meson.build_

Allow newlib compilation for CPUs not maintained by picolibc.
Also _or1k_ contains _exception.c_ from libbase, as it is or1k specific and there were no place to put it without major changes.

#### _iob.c_

Moved most of _libbase/console.c_ logic here. Contains `__iob` array required by picolibc.

#### _missing.c_

When compiling for lm32 and mor1kx, there were linking errors about missing functions. Seems that we have to provide defintions for `getpid`, `kill` and `_exit` to get it linked. Those are only minimal variants to get it linking. There may be more elegant solution to this.

It worked without those on riscv CPUs.

### _software/libbase_

Completly removed. Remaining files were moved to _software/libutils_ and _software/libcomm_.

__libcomm__ contains functions used for communicating via different interfaces. When __liblitespi__ is finished _spiflash.c_ will be probably removed from here.

__libutils__ has stuff used in many places, like CRC calculation, memtests or progressbars.

### _software/include_

Only _include/hw_ is left. Everything else was either removed or moved to _libutils_/_libcomm_.

### Other changes

Enabled global LTO. Some files have it disabled to prevent functions from being optimized out.

Replaced all `readchar` calls with `getchar`, and `putsnonl` with `fputs(s, stdout)`.

Picolibc requires system includes so `-nostdinc` was removed from `CFLAGS`.

_crt0.o_ is now compiled by _bios/Makefile_.

### CODE REVIEW

**Comment by mithro** [comment]
@michalsieron - If we end up going this path should probably provide picolibc via a pythondata-software package like https://github.com/litex-hub/pythondata-software-compiler_rt

**Comment by mithro** [comment]
FYI - @kgugala @mateusz-holenko

**Comment by mithro** [comment]
FYI - @tcal-x @JosephBushagour @danc86 @alanvgreen

**Comment by michalsieron** [comment]
# PR status update

With latest commits it compiles and runs on vexriscv (probably any riscv), lm32 and mor1kx.
I tested it only on _digilent_arty.py_ script, but I think it should work with others too.
By saying it **runs**, I mean that I can enter commands, like reboot or change leds value.
That's all testing I did, so it is not done yet.

Below I list changes and their descriptions.

## *litex_setup.py*
I added pythondata-software-picolibc to downloaded repositories. It it contains picolibc repo as its submodule, so when installing we get newest picolibc. Might need to change that to use released versions to be more stable.

Other changes to *litex_setup.py* should be probably discarded, as they were there only to make setup easier.

## _libc_
There is a new directory _litex/soc/software/libc_, which contains stuff needed for picolibc to compile and work:

### _Makefile_
Outside of running meson commands for picolibc compilation, it also creates cross.txt file, which is necessary for meson config.

### _\<cpu\>-meson.build_
Allow newlib compilation for CPUs not maintained by picolibc.

### _iob.c_
I moved most of _libbase/console.c_ logic here. I **did not** move or rename _base/console.h_ header file, so that may be next thing to change.

### _missing.c_
When compiling for lm32 and mor1kx, I got linking errors about missing functions. Seems that we have to provide defintions for `getpid`, `kill` and `_exit` to get it linked. As I threw in there anything, just to make linker happy, it should be looked at and modified by someone with more knowledge than me.

I do not know, why it worked without those on riscv CPUs.

## Other changes

### Includes
I removed `$(SOC_DIRECTORY)/software/include/base` from include directories. It was conflicting with picolibc compilation. Instead I put, picolibc include directories there.

I also removed `-nostdinc` for the same reason.

### `readchar`/`putsnonl`
Due to the changes in _libbase/console.c_, I replaced all `readchar` calls with `getchar`, and `putsnonl` with `fputs(s, stdout)`. It allowed me to completly remove libbase specific IO functions.

### libbase-nofloat
I removed libbase-nofloat variant from Makefiles and _builder.py_ script. Instead picolibc is being compiled with `-DPRINTF_LEVEL=1`, which disables float support.

**Comment by mithro** [comment]
The primary question is how does it change the BIOS / firmware file size?

**Comment by michalsieron** [comment]
Building with toolchain created with OpenADK - `(GCC) 12.0.0 20210729 (experimental)` 
`libbase` is `enjoy-digital/master`
`picolibc` is `antmicro/libbase-replacement`
`picolibc+ioll` has `-Dio-long-long=true` switched on for issue #322 

|             | RAM / ROM usage |              |               | Relative usage | |
|-------------|:---------------:|:------------:|:-------------:|-----------------|-----------------|
| CPU         | libbase         | picolibc     | picolibc+ioll |     picolibc    |  picolibc+ioll  |
| serv        | 27.57 / 1.43    | 27.01 / 1.41 | 27.54 / 1.41  | -2.03% / -1.40% | -0.11% / -1.40% |
| femtorv     | 27.57 / 1.43    | 27.01 / 1.41 | 27.54 / 1.41  | -2.03% / -1.40% | -0.11% / -1.40% |
| ibex        | 20.72 / 1.43    | 20.38 / 1.41 | 20.78 / 1.41  | -1.64% / -1.40% | +0.29% / -1.40% |
| cv32e40p    | 21.79 / 1.70    | 21.45 / 1.68 | 21.85 / 1.68  | -1.56% / -1.18% | +0.28% / -1.18% |
| minerva     | 26.89 / 1.70    | 26.32 / 1.68 | 26.82 / 1.68  | -2.12% / -1.18% | -0.26% / -1.18% |
| vexriscv    | 26.98 / 1.70    | 26.40 / 1.68 | 26.90 / 1.68  | -2.15% / -1.18% | -0.30% / -1.18% |
| picorv32    | 27.48 / 2.83    | 26.90 / 2.82 | 27.39 / 2.82  | -2.11% / -0.35% | -0.33% / -0.35% |
| rocket      | 22.77 / 1.72    | 22.53 / 1.70 | 22.54 / 1.70  | -1.05% / -1.16% | -1.01% / -1.16% |
| blackparrot | 27.02 / 1.45    | 26.49 / 1.43 | 26.51 / 1.43  | -1.96% / -1.38% | -1.89% / -1.38% |
| lm32        | 29.87 / 1.70    | 29.67 / 1.81 | 30.69 / 1.81  | -0.67% / +6.47% | +2.75% / +6.47% |
| mor1kx      | 39.73 / 1.70    | 39.89 / 1.69 | 40.75 / 1.69  | +0.40% / -0.59% | +2.57% / -0.59% |
| microwatt   | 35.37 / 1.46    | -  /    -            | -  /    -             |    -   /    -   |    -   /    -   |
| zynq7000    | -  /    -               | -  /    -            | -  /    -             |    -   /    -   |    -   /    -   |

**Comment by mithro** [comment]
If I'm understanding things correctly, picolibc is smaller in almost all cases apart from lm32?

**Comment by mithro** [comment]
What is OpenADK?

**Comment by michalsieron** [comment]
I just updated table with microwatt. There were missing definitions and now it compiles. I'll push commit later.

[OpenADK](https://openadk.org/) is toolchain builder like buildroot. At least that's what I understand and how I use it.

**Comment by mithro** [comment]
We should be testing with the toolchains available via https://github.com/hdl/conda-compilers too

**Comment by michalsieron** [comment]
I also tried enabling LTO and results are promising.

Here picolibc is compiled with `-Dio-long-long=true` to support `long long` in IO functions and with `-flto`.

Results are in KiB.

|             | RAM / ROM usage |              |                   |
|-------------|-----------------|--------------|-------------------|
| CPU         | libbase         | picolibc     |  relative gain    |
| serv        | 27.57 / 1.43    | 24.47 / 1.34 | -11.24%  / -6.29% |
| femtorv     | 27.57 / 1.43    | 24.47 / 1.34 | -11.24%  / -6.29% |
| ibex        | 20.72 / 1.43    | 18.61 / 1.34 | -10.18%  / -6.29% |
| cv32e40p    | 21.79 / 1.70    | 19.72 / 1.60 | -9.50%   / -5.88% |
| minerva     | 26.89 / 1.70    | 23.82 / 1.60 | -11.42%  / -5.88% |
| vexriscv    | 26.98 / 1.70    | 23.89 / 1.60 | -11.45%  / -5.88% |
| picorv32    | 27.48 / 2.83    | 24.39 / 2.74 | -11.24%  / -3.18% |
| rocket      | 22.77 / 1.72    | 20.07 / 1.60 | -11.86%  / -6.98% |
| blackparrot | 27.02 / 1.45    | 23.30 / 1.34 | -13.77%  / -7.59% |
| lm32        | 29.87 / 1.70    | 27.10 / 1.73 | -9.27%   / +1.76% |
| mor1kx      | 39.73 / 1.70    | 36.32 / 1.60 | -8.58%   / -5.88% |
| microwatt   | 35.37 / 1.46    | 29.32 / 1.34 | -17.10%  / -8.22% |
| zynq7000    | - / -               | - / -            | -        / -      |

Compilation is successful, but I only tested vexriscv and serv versions on Arty A7 and there were some minor issues with printed text so it will need some work.

**Comment by michalsieron** [comment]
I ran into some issues with demo app with these changes. Boot sequence stops after **Liftoff!** message.
I believe it is similar to issues #856 and #876, as it also seems to stop at `uart_sync`.
Sadly fix I mentioned there doesn't work in this case.

**Comment by michalsieron** [comment]
Fixed the issue mentioned in previous comment. Turns out with LTO enabled, `_start` didn't land at the beginning and jump from BIOS didn't work properly.

**Comment by mateusz-holenko** [comment]
@michalsieron Could you rebase the branch?

**Review by enjoy-digital — APPROVED** [review]
Most of the changes look good. Without doing precise measurements, it also seems faster on hardware and simulation and I haven't seen regression.

picolibc seems to be a good choice for LiteX and merging this PR will also ease reuse of other libc implementation in the future, so I'm going to merge it.

This downside is that it adds 125MB of dependency to the project and slow down BIOS compilation, but it will fix issues we don't necessarily want to spend time on, so let's go ahead.

I just think we should minimize changes for users using bare metal application with LiteX, so don't think it's the right time to rename the libraries  and we can also easily provide `readchar`/`putsnonl` retro-compatibility. I'll push changes on this.

In the future, it would also be good to generate CPU Family directly from the CPU code and see if the custom meson builds can be moved to the CPU directories.

**Pull request merged**
