### PR TITLE
DFUProg now checks and propagate return codes of called executables...

### PR DESCRIPTION
**Pull request by fidergo-stephane-gourichon**
…so that failure gets noticed.

And adjust some caller scripts that happen to be in same repo.

### CODE REVIEW

**Comment by fidergo-stephane-gourichon** [comment]
For caller scripts that don't test for the return value of DFUProg.load_bitstream(), they won't benefit but at least this change is non-breaking.

**Comment by enjoy-digital** [comment]
@fidergo-stephane-gourichon: indeed, that's also what i want to implement. Sorry for the delay, i haven't forgotten the PR but haven't been able to look at it yet.

**Comment by enjoy-digital** [comment]
@fidergo-stephane-gourichon: just for info, i started added more checks and improving error reporting for the toolchain's calls with https://github.com/enjoy-digital/litex/commit/db836e8e5d9d66caade9294f1a8b67eb2b4d3611. I'll do the same on the programmers soon.

**Comment by enjoy-digital** [comment]
Thanks @fidergo-stephane-gourichon for the feedback and proposed PR, with https://github.com/enjoy-digital/litex/commit/2741fc2ba52aa1b98f8c1ab76d69278555b4e1f6 we now no longer silently ignore the programming errors.

**Pull request closed without merging**
