### PR TITLE
core/naxriscv provide a deployable NaxRiscv SMP

### PR DESCRIPTION
**Pull request by Dolu1990**
Support multi core / coherent dma, can run doom on debian.

### CODE REVIEW

**Comment by Dolu1990** [comment]
On digilent nexys video, dual core RV64GC debian ready : 
python3 -m litex_boards.targets.digilent_nexys_video --cpu-type=naxriscv  --bus-standard axi-lite --with-video-framebuffer --with-coherent-dma --with-sdcard --with-ethernet --xlen=64 --scala-args='rvc=true,rvf=true,rvd=true,alu-count=2,decode-count=2'  --with-jtag-tap --sys-clk-freq 100000000 --cpu-count 2  --build --load

**Comment by Dolu1990** [comment]
That's is weird, seems like the ci doesn't look at litex_setup.py for the install ?

I can see : 
 Cloning into 'pythondata-cpu-naxriscv'...
Already on 'master'

while litex_setup.py is : 
"pythondata-cpu-naxriscv": GitRepo(url="https://github.com/litex-hub/", branch="smp"),

**Comment by enjoy-digital** [comment]
Thanks @Dolu1990! Sorry for the issue with the CI. I'll look at it. Thanks also @cklarhorst for the PR, I'll see if we can try to also use `--dev `mode for this instread of introducing a new argument.

**Comment by Dolu1990** [comment]
No worries, thanks ^^
Related to debian stuff, i documented it there : 
https://github.com/SpinalHDL/NaxSoftware/tree/main/debian2

Will, it will likely move on this repo in another folder.

**Pull request merged**
