### PR TITLE
Ussysmon: SYSMONE1 for US devices

### PR DESCRIPTION
**Pull request by jersey99**
Verified correct reporting of a few VCC voltages and Temperature, without expose_drp on an htg940

Things that would be nice to do:
1. Add a way to assign a USER bank voltage monitor from the constructor
2. Don't duplicate code between XADC and here.
3. Verify limits of Alarms [Make them settable from constructor?]
3. ADD SYSMONE4 [The ultrascale-plus version of XADC]. I don't have a USP board on me.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @jersey99, this will be very useful. It looks good to me, I'll review it more carefully next week, test it and merge it (and maybe try to move it in xadc.py).

**Comment by jersey99** [comment]
@enjoy-digital Thanks for taking a look. I spent a little time, and moved USSYSMON into xadc.py. Hopefully that eases what you need to do next week.

**Review by enjoy-digital — APPROVED** [review]
Thanks @jersey99 for the merge in `xadc.py`, this looks good.

**Comment by enjoy-digital** [comment]
@jersey99: This is merged, I just did minor changes in https://github.com/enjoy-digital/litex/commit/04cb8e0e5e745e54daddf84e08deca561b7edec3. The only change that is relevant for userq is USSYSMON renamed to USSystemMonitor.

**Pull request merged**
