### PR TITLE
Add new SoC/LiteXSoC classes and use it for SoCCore/SoCSDRAM

### PR DESCRIPTION
**Pull request by enjoy-digital**
As described in https://github.com/enjoy-digital/litex/issues/372, a refactor of the SoC classes was needed to cleanup the code and allow future improvements. In this PR New SoC/LiteXSoC classes are introduced and used as base to provide SoCCore/SoCSDRAM full retro-compatbility. No changes should be required on User's designs.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
This has been tested in retro-compatibility mode with most of the designs i maintain or have access to. This already provides useful reporting while building the SoC so i'm merging to go further and start using new features/possibilities.

**Comment by enjoy-digital** [comment]
FYI @mithro, @xobs, @mateusz-holenko : the only thing i saw that is not supported by the retro-compatibility layer is the support of `address_decoder` provided to `add_wb_slave`. I'm not sure it's easy to provide retro-compatibility for it and the change on the user's side is easy: just pass the `address` instead of the `address_decoder` as done in https://github.com/litex-hub/litex-boards/commit/c94360c2e0c0bc95a059b66199e5fbbf033bb75c. I saw you were using it in your design, so will probably have to do these small changes when using upstream LiteX. I hope you won't have others changes to do, please open PR if so.

**Comment by xobs** [comment]
There was a regression in soc/doc and the svd generator, which I fixed.

Because this breaks lxsocdoc, I've posted a note saying the project is now deprecated and integrated into litex: https://github.com/litex-hub/lxsocdoc

**Comment by enjoy-digital** [comment]
@xobs thanks for the feedback and lxsocdoc update. The regression was not volontary and we could also have added retro-compatibility to SoCCore if needed, sorry for that. Now that lxsocdoc is merged we would have probably deprecated it at some point to ease maintenance, so if you think that's the right time to do it, let's do that.

**Pull request merged**
