### PR TITLE
cpu/vexiiriscv integration

### PR DESCRIPTION
**Pull request by Dolu1990**
Do not merge yet (WIP)

Hi,
This PR add VexiiRiscv in Litex. Here is an example to generate a quad-core linux capable RISC-V on digilent_nexys_video : 

(single issue, RV32IMASU, linux ready, performances look quite good so far)

```shell
python3 -m litex_boards.targets.digilent_nexys_video --soc-json build/digilent_nexys_video/csr.json --cpu-type=vexiiriscv  --vexii-args="--allow-bypass-from=0 --debug-privileged --with-mul --with-div --div-ipc --with-rva --with-supervisor --performance-counters 0 --fetch-l1 --fetch-l1-ways=4 --lsu-l1 --lsu-l1-ways=4 --fetch-l1-mem-data-width-min=64 --lsu-l1-mem-data-width-min=64  --with-btb --with-ras --with-gshare --relaxed-branch --regfile-async --lsu-l1-refill-count 2 --lsu-l1-writeback-count 2 --lsu-l1-store-buffer-slots=2 --lsu-l1-store-buffer-ops=32 --with-lsu-bypass" --cpu-count=4 --with-jtag-tap  --with-video-framebuffer --with-sdcard --with-ethernet --with-coherent-dma --l2-bytes=262144
```

Todo : 
- [x] FPU
- [x] Debian

### CODE REVIEW

**Comment by Dolu1990** [comment]
Here is an example of a debian ready dual core (WIP) : 

```scala
python3 -m litex_boards.targets.digilent_nexys_video --cpu-type=vexiiriscv  --with-jtag-tap  --bus-standard axi-lite --vexii-args=" \
--allow-bypass-from=0 --debug-privileged --with-mul --with-div --div-ipc --with-rva --with-supervisor --performance-counters 0 \
--regfile-async --xlen=64 --with-rvc --with-rvf --with-rvd --fma-reduced-accuracy \
--fetch-l1 --fetch-l1-ways=4 --fetch-l1-mem-data-width-min=64 \
--lsu-l1 --lsu-l1-ways=4  --lsu-l1-mem-data-width-min=64 --lsu-l1-store-buffer-ops=32 --lsu-l1-refill-count 2 --lsu-l1-writeback-count 2 --lsu-l1-store-buffer-slots=2  --with-lsu-bypass \
--with-btb --with-ras --with-gshare --relaxed-branch"  --cpu-count=2 --with-jtag-tap  --with-video-framebuffer --with-sdcard --with-ethernet --with-coherent-dma --l2-byte=131072 --update-repo=no  --sys-clk-freq 100000000 --build   --load
```

**Comment by Dolu1990** [comment]
Updated it with 3 base variant : 
cached, linux, debian

On digilent video : 
```shell
# debian ready : 
python3 -m litex_boards.targets.digilent_nexys_video --cpu-type=vexiiriscv --cpu-variant=debian  --cpu-count=1 --with-video-framebuffer --with-sdcard --with-ethernet --with-coherent-dma --build --load

#debian ready with more perf 
python3 -m litex_boards.targets.digilent_nexys_video --cpu-type=vexiiriscv --cpu-variant=debian --bus-standard axi-lite --vexii-args="--regfile-async --lsu-l1-store-buffer-ops=32 --lsu-l1-refill-count 2 --lsu-l1-writeback-count 2 --lsu-l1-store-buffer-slots=2" --cpu-count=4 --with-jtag-tap  --with-video-framebuffer --with-sdcard --with-ethernet --with-coherent-dma --l2-byte=262144  --build --load
```

**Comment by Dolu1990** [comment]
@enjoy-digital 
Hi,
I think this is ok for merge now :)

**Review by enjoy-digital — APPROVED** [review]
Awesome, thanks @Dolu1990!

**Comment by Dolu1990** [comment]
Documentation about how to deploy buildroot / debian here : 
- https://github.com/SpinalHDL/VexiiRiscv/tree/dev/doc/litex/debian
- https://github.com/SpinalHDL/VexiiRiscv/tree/dev/doc/litex/buildroot

**Comment by enjoy-digital** [comment]
Great, thanks @Dolu1990!

**Pull request merged**
