### PR TITLE
WIP: Support for a SPI flash module system

### PR DESCRIPTION
**Pull request by mithro**
Currently a WIP, want feedback before merging. This is one of the things needed to bring the [litex-buildenv platforms](https://github.com/timvideos/litex-buildenv/tree/master/platforms) into the [`litex-boards`](https://github.com/litex-hub/litex-boards).

Support for SPI NOR flash module system similar to how [the SDRAM module system works](https://github.com/enjoy-digital/litedram/blob/master/litedram/modules.py). It has;
 - [x] Enums for the SPI Flash manufacturer IDs in the `litex.soc.cores.spi.ids` module.
 - [x] Structures for the SPI Flash operation codes in the `litex.soc.cores.spi.opcodes` module.
 - [x] Structures for the SPI Flash protocols (data rates, pins, etc) module.
 - [x] Module for describing SPI NOR Flash modules include name, IDs, opcodes, size, etc.
 - [ ] Description of all features needed by the [SPI NOR Flash execute in place module](https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/spi_flash.py).
 - [ ] Integration with the [`litex-boards`](https://github.com/litex-hub/litex-boards) and other platform descriptions.

Data is based on [OpenOCD](https://github.com/openrisc/openOCD/blob/master/src/flash/nor/spi.c) and [Linux](https://github.com/torvalds/linux/blob/master/drivers/mtd/spi-nor/spi-nor.c) data tables.

### CODE REVIEW

**Comment by DurandA** [comment]
Can we have a glimpse on how this will work? I noticed that none of the [latex-boards](https://github.com/litex-hub/litex-boards) targets contain a *spiflash* flash module (unlike this custom [*TinyFPGA LiteX* target](https://github.com/kekiefer/tinyfpga-litex/blob/master/tinyfpga_litex.py)).

**Comment by mithro** [comment]
@DurandA - It will eventually be similar to how LiteDRAM does DDR modules. This is an attempt to get the [litex-buildenv platform files](https://github.com/timvideos/litex-buildenv/tree/master/targets) in [sync with the litex-boards](https://github.com/litex-hub/litex-boards).

**Comment by mithro** [comment]
@DurandA Still very much a work in progress.

**Comment by enjoy-digital** [comment]
The work is now ongoing in https://github.com/litex-hub/litespi, i think we can close this.

**Pull request closed without merging**
