### PR TITLE
SPIMaster: Added support for different CPOL/CPHA

### PR DESCRIPTION
**Pull request by ilya-epifanov**

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks, it seems fine for CPOL, but i don't think it's correct for CPHA, because in the case of CPOL=1, CPHA=1, CPOL ^ CPHA = 0 so the behavior will be similar to CPOL=0, CPHA=0.

**Comment by ilya-epifanov** [comment]
@enjoy-digital yep, it's WIP. should be easy to code, but I have to verify it with an LA.

**Comment by sergachev** [comment]
Note: there is an implementation of SPI Master in MiSoC which supports this and is naturally easy to use with LiteX: https://github.com/m-labs/misoc/blob/master/misoc/cores/spi.py

**Comment by enjoy-digital** [comment]
@ilya-epifanov: i'm closing since some work would still need to be done to get it working and as @sergachev others alternative core could be used, but please create another PR if you have a working implementation.

**Pull request closed without merging**
