### PR TITLE
Standardizing `cpu_variants` and adding lots of documentation

### LINKED ISSUE #159: Standardize variant names across different CPU types?
[VexRISCV uses]()
`        variants = ("std", "std_debug", "lite", "lite_debug", "min", "min_debug")`

[picorv32 uses;]()
`        variant == "minimal":`

[mor1kx uses](https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/cpu/mor1kx/core.py#L16)
`        assert variant in (None, "linux"), "Unsupported variant %s" % variant`

[lm32 uses](https://github.com/enjoy-digital/litex/blob/master/litex/soc/cores/cpu/lm32/core.py#L16):
`        assert variant in (None, "lite", "minimal"), "Unsupported variant %s" % variant`

I had some older thoughts at https://github.com/timvideos/litex-buildenv/wiki/CPU-Variants

I think we need;
 * `minimal`
 * `standard`
 * `linux`
 * `debug` versions (?)

### PR DESCRIPTION
**Pull request by mithro**
* Fixes #159
 * [Documentation of Soft-CPU types and variants](https://github.com/mithro/litex/blob/cpu-docs/doc/Soft-CPU.md)
 * [Documentation of Firmware types](https://github.com/mithro/litex/blob/cpu-docs/doc/Firmware.md)

The documentation is pulled from the [LiteX-BuildEnv Wiki](https://github.com/timvideos/litex-buildenv/wiki).

### CODE REVIEW

**Comment by mithro** [comment]
Just working on getting Travis to be green.

**Comment by mithro** [comment]
This pull request now works on travis! See the test output below;
```
test_simultaneous (test.test_axi_lite.TestAXILite) ... ok
test_write_read (test.test_axi_lite.TestAXILite) ... ok
test_burst2beat (test.test_axi.TestAXI) ... ok
test_arty (test.test_targets.TestTargets) ... ok
test_bad_variant_extension (test.test_targets.TestTargets) ... Traceback (most recent call last):
  File "litex/boards/targets/simple.py", line 81, in <module>
    main()
  File "litex/boards/targets/simple.py", line 75, in main
    soc = cls(platform, **soc_core_argdict(args))
  File "litex/boards/targets/simple.py", line 23, in __init__
    **kwargs)
  File "/home/travis/build/mithro/litex/litex/soc/integration/soc_core.py", line 221, in __init__
    raise InvalidCPUExtensionError(cpu_variant)
litex.soc.integration.soc_core.InvalidCPUExtensionError: Invalid extension in cpu_variant value: standard+bad
Possible Values:
 - debug
ok
test_bad_variants (test.test_targets.TestTargets) ... Traceback (most recent call last):
  File "litex/boards/targets/simple.py", line 81, in <module>
    main()
  File "litex/boards/targets/simple.py", line 75, in main
    soc = cls(platform, **soc_core_argdict(args))
  File "litex/boards/targets/simple.py", line 23, in __init__
    **kwargs)
  File "/home/travis/build/mithro/litex/litex/soc/integration/soc_core.py", line 216, in __init__
    raise InvalidCPUVariantError(cpu_variant)
litex.soc.integration.soc_core.InvalidCPUVariantError: Invalid cpu_variant value: bad
Possible Values:
 - minimal (aliases: min)
 - lite (aliases: light, zephyr, nuttx)
 - standard (aliases: None, std)
 - full (aliases: )
 - linux (aliases: )
ok
test_de0nano (test.test_targets.TestTargets) ... ok
test_genesys2 (test.test_targets.TestTargets) ... ok
test_kc705 (test.test_targets.TestTargets) ... ok
test_kcu105 (test.test_targets.TestTargets) ... ok
test_minispartan6 (test.test_targets.TestTargets) ... ok
test_nexys4ddr (test.test_targets.TestTargets) ... ok
test_nexys_video (test.test_targets.TestTargets) ... ok
test_simple (test.test_targets.TestTargets) ... ok
test_variants_lm32 (test.test_targets.TestTargets) ... skipped 'No lm32 toolchain on Travis-CI'
test_variants_or1k (test.test_targets.TestTargets) ... skipped 'No or1k toolchain on Travis-CI'
test_variants_riscv (test.test_targets.TestTargets) ... ok
test_versa_ecp5 (test.test_targets.TestTargets) ... ok
test_versa_ulx3s (test.test_targets.TestTargets) ... ok
test_comma (test.test_code_8b10b.TestLineCoding) ... ok
test_no_spurious_commas (test.test_code_8b10b.TestLineCoding) ... ok
test_roundtrip (test.test_code_8b10b.TestLineCoding) ... ok
test_running_disparity (test.test_code_8b10b.TestLineCoding) ... ok
test_csr_status (test.test_csr.TestCSR) ... ok
test_csr_storage (test.test_csr.TestCSR) ... ok
test_gearbox (test.test_gearbox.TestGearbox) ... ok
```

**Comment by enjoy-digital** [comment]
Thanks @mithro,

I just also started a wiki and would think the documentation would probably be better there for now. This documentation will be different and less exhaustive than the one in litex-buildenv (and i want to reditect to the litex-buildenv documentation for more informations/examples), but maybe we could share the parts in your pull  request? If that's ok for you, can you remove the documentation part of this pull request, i'll merge the CPU variant changes and i'll integrate this documentation in the LiteX wiki.

**Comment by mithro** [comment]
I think having a copy of these files inside the code repository is useful because it appears when you do a grep through the source code...

**Comment by enjoy-digital** [comment]
I'm fine with that, but then can we copy this in the LiteX wiki and do the pull from it?

**Comment by enjoy-digital** [comment]
In fact i'll merge, keep the pull from litex_builenv and will just also put that on LiteX wiki, updating the wiki while updating the repo. Thanks for all the work.

**Comment by enjoy-digital** [comment]
@mithro: in some previous work you did, you were handling the CPU properties differently than what i did (i just realized a few days ago you did something similar): https://github.com/enjoy-digital/litex/compare/master...mithro:cpu-config. Is the current way to do it ok for you or do you have a preference for the way you did it?

**Comment by mithro** [comment]
@enjoy-digital I had totally forgotten about that patch.... I do think it is probably a "better" solution in the longer term but what we have now is okay...

**Pull request merged**
