### PR TITLE
Json2dts fixes

### PR DESCRIPTION
**Pull request by geertu**
A few whitespace fixes, and 3 fixes for issues detected by dt-schema validation.

### CODE REVIEW

**Comment by geertu** [comment]
plic and liteuart tested on OrangeCrab.

**Comment by gsomlo** [comment]
@geertu, do you want to add another commit to also take care of `mac0`? That one still comes back as

```
                compatible = "litex,liteeth";
                reg = <
                    0x12001000 0x7c
                    0x12001800 0x0a
                    0x30000000 0x2000>;
                tx-fifo-depth = <2>;
                rx-fifo-depth = <2>;
                interrupts = <2>;
                status = "okay";
```

It's that discrepancy that made me screw it all up in the first place :smiley:
LMK and I can do it if you'd rather not. Othewise, LGTM.

**Review by enjoy-digital — APPROVED** [review]
Thanks @geertu.

**Comment by geertu** [comment]
@gsomlo mac0 should be OK again after 37704195af3b5323471e67bad01209f7432fe8ce

**Pull request merged**
