### PR TITLE
demo: more helpful usage message / support Altera JTAG in litex_term

### PR DESCRIPTION
**Pull request by hansfbaier**
I spent about half an hour trying to figure out, how the demo creator is supposed to being
used and I hope this usage message will save others the time.

### CODE REVIEW

**Comment by hansfbaier** [comment]
Hi Florent, 
I also implemented support for Altera UART over JTAG in litex_term:
```
        __   _ __      _  __
       / /  (_) /____ | |/_/
      / /__/ / __/ -_)>  <
     /____/_/\__/\__/_/|_|
   Build your hardware, easily!

 (c) Copyright 2012-2020 Enjoy-Digital
 (c) Copyright 2007-2015 M-Labs

 BIOS built on Feb  6 2021 06:01:00
 BIOS CRC passed (d38fa215)

 Migen git sha1: --------
 LiteX git sha1: --------

--=============== SoC ==================--
CPU:            VexRiscv @ 50MHz
BUS:            WISHBONE 32-bit @ 4GiB
CSR:            32-bit data
ROM:            32KiB
SRAM:           8KiB
L2:             8KiB
SDRAM:          32768KiB 16-bit @ 100MT/s (CL-2 CWL-2)

--========== Initialization ============--
Initializing SDRAM @0x40000000...
Switching SDRAM to software control.
Switching SDRAM to hardware control.
Memtest at 0x40000000 (2MiB)...
  Write: 0x40000000-0x40200000 2MiB     
   Read: 0x40000000-0x40200000 2MiB     
Memtest OK
Memspeed at 0x40000000 (2MiB)...
  Write speed: 12MiB/s
   Read speed: 11MiB/s

--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
[LXTERM] Received firmware download request from the device.
[LXTERM] Uploading ../litex-boards/demo/demo.bin to 0x40000000 (9256 bytes)...
[LXTERM] Upload complete (0.2KB/s).
[LXTERM] Booting the device.
[LXTERM] Done.
Executing booted program at 0x40000000

--============= Liftoff! ===============--

LiteX minimal demo app built Feb  6 2021 06:46:50

Available commands:
help               - Show this command
reboot             - Reboot CPU
led                - Led demo
donut              - Spinning Donut demo
litex-demo-app> led
Led demo...
Counter mode...
Shift mode...
Dance mode...
litex-demo-app> 
```
I reckon this probably shoud have been two different pull requests.

**Comment by hansfbaier** [comment]
P.S.: I tested the code changes also with the de0_nano board over FTDI usb serial, and it still works fine.

**Review by enjoy-digital — APPROVED** [review]
Thanks @hansfbaier, this will be very useful on Altera/Intel board without a default UART (ex De0Nano that I really like but don't use that much because I always forget out to plug the external UART..., this will no longer be the case :) ) I'll just remove a comment in demo.py since not true: `--build-path` is here to allow user to call `litex_bare_metal_demo` from anywhere, not only the project directory.

**Comment by enjoy-digital** [comment]
@hansfbaier: I just understood why you added this comment, absolute paths were indeed not correctly supported, this is now supported with https://github.com/enjoy-digital/litex/commit/5430c1455e2dc27e576542cc3632b320f4617dd5 and should simplify `litex_bare_metal_demo` use, thanks for the feedback.

**Comment by hansfbaier** [comment]
@enjoy-digital Awesome! Thanks!

**Pull request merged**
