### PR TITLE
add docstrings to bitbang

### PR DESCRIPTION
**Pull request by jeremyherbert**
Hi,

I asked on the discord how to add documentation to litex, and the suggestion was to start by adding some docstrings. I have had a go at a small file here (`bitbang.py`), and I would appreciate any feedback on this. I would also like to know if the following would be accepted:

- Changes to whitespace to bring the files in line with PEP8
- Inline typehints where possible

Thanks.

### CODE REVIEW

**Comment by jeremyherbert** [comment]
I have just updated the file with PEP8 whitespace fixes (as far as I can tell) and type hints. The type hints exist mostly for IDEs like VSCode or Pycharm and shouldn't break anything because the python versions that don't support type hints are all obsolete. In particular, I have found type hints to be more useful for newbies because the IDE can at least warn you that you are probably doing something silly.

**Comment by enjoy-digital** [comment]
Thanks @jeremyherbert, I now see what you meant with whitespaces, but in fact we'll keep this since I like to align things to improve code presentation. Type hints could be interesting and I'll think about it and we'll maybe wait a bit to add them (this should probably done globally)).

**Comment by enjoy-digital** [comment]
Thanks @jeremyherbert, I now see what you meant with whitespaces, but in fact we'll keep this since I like to align things to improve code presentation. Type hints could be interesting and I'll think about it and we'll maybe wait a bit to add them (this should probably done globally)).

**Comment by enjoy-digital** [comment]
@jeremyherbert: I merged the PR but reverted the last commit and just did minor cosmetic changes on top of your first commit with https://github.com/enjoy-digital/litex/commit/38282effd48ae6cf85c22cf6ec98b37e0f28523d. Regarding adding type hints, I'll still consider it but that's maybe not the right moment to add it to a single core.

Thanks a lot for your contribution!

**Pull request merged**
