### PR TITLE
cpu/rocket/core: Remove ResetInserter on adapters.

### PR DESCRIPTION
**Pull request by enjoy-digital**
Previously, the SoCController was only reseting the CPU, which required adding
these ResetInserters. Now that the SoCController resets both CPU and peripherals
these ResetInserters are redundant and no longer useful.

### CODE REVIEW

**Comment by gsomlo** [comment]
looks fine (and worked fine when I tested it on nexys4ddr: writing to the reset register from the bios resulted in a well-behaved reset, and so did hitting the designated hardware reset button).

One question: should https://github.com/enjoy-digital/litex/blob/master/litex/soc/integration/soc.py#L1337 also be addressed as part of this change?

**Comment by enjoy-digital** [comment]
Thanks @gsomlo for the feedback. I was indeed almost sure there was something another location for this :) We should indeed also remove it. I updated the PR, can you do a test with it?

**Comment by gsomlo** [comment]
On Mon, Sep 27, 2021 at 06:47:24AM -0700, enjoy-digital wrote:
> I updated the PR, can you do a test with it?

Tested with linuxd (128-bit mem width) on nexys4ddr (64-bit litedram
width), still works fine. I think we're good to go!

**Comment by enjoy-digital** [comment]
Thanks @gsomlo, that's merged.

**Pull request merged**
