### PR TITLE
Support SPI-mode SDCard booting on Litex+Rocket (64bit) configuration

### PR DESCRIPTION
**Pull request by gsomlo**
specifically targeted at (and successfully tested on) nexys4ddr, but should work on other boards as well

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks, i've been able to test it with Linux-on-LiteX-Vexriscv.

**Comment by rob-ng15** [comment]
Just out of curiosity, are there specific unit8t, uint16t, uint32t types in
the Litex environment, would I be better off using those throughout my spi
sd card bitbanging code?

My question is regards the partition table and directory structures, as the
members in those structures are a predefined size.

If so, I'll happily provide a patch for more portability.

I'm pleased to see my patch being adapted and used by others.

Rob.

**Comment by gsomlo** [comment]
> Just out of curiosity, are there specific unit8t, uint16t, uint32t types in the Litex environment, would I be better off using those throughout my spi sd card bitbanging code? My question is regards the partition table and directory structures, as the members in those structures are a predefined size. If so, I'll happily provide a patch for more portability.

https://github.com/enjoy-digital/litex/blob/master/litex/soc/software/include/base/stdint.h#L11

Thanks,
--Gabriel

**Comment by rob-ng15** [comment]
OK thanks.

I'll update and test. Got an airport run to do, so may be a couple of
hours.

**Comment by rob-ng15** [comment]
Have made a patch, tested on de10nano.

https://github.com/enjoy-digital/litex/pull/434

**Pull request merged**
