### PR TITLE
bios: print memory usage

### PR DESCRIPTION
**Pull request by fjullien**
Print memory usage during the compilation of bios.elf.
Introduce a dependancy on pyelftools.

### CODE REVIEW

**Comment by mithro** [comment]
Could this be an optional extra if `pyelftools` is installed?

@xobs - This seems pretty useful for things like the Fomu where space can be pretty tight.
@ewenmcneill - You might want to take a look at this too...

**Comment by xobs** [comment]
The main advantage this seems to have over running `size` is that it looks like it includes the maximum region sizes, whereas `size` does not:

```
> riscv64-unknown-elf-size .\build\software\bios\bios.elf
   text    data     bss     dec     hex filename
   6444     168    4440   11052    2b2c .\build\software\bios\bios.elf
[9:41:33 AM] D:/Code/Fomu/foboot/hw>
```

It looks like this is an optional extra already, because it can only be invoked using `-m`, similar to how other software packages such as `litex_server` can rely on libusb.  I imagine this would be a great jumping-off point for people who want to do deeper introspection on their ELF binary to figure out where all that space is going.

The other trick I use to figure out what's eating space on Fomu is `nm --size-sort | tail`, which could be a nice addition to litex tools later on down the road.

As @mithro said though, I would prefer that we kept it as an optional feature.

**Comment by fjullien** [comment]
I could also remove the dependency on `pyelftools` and use `readelf` or `size` to get size of different sections.

**Comment by enjoy-digital** [comment]
@fjullien: if you find a way to do the same without the extra dependency, we could avoid making it optional and always enable it.

**Comment by fjullien** [comment]
I updated this PR. It now uses `readelf` to get numbers.
I chose `readelf` over `size` in case we want to do something special with each section.

**Comment by enjoy-digital** [comment]
Thanks for the update. It's working correctly on 32-bit processors (i tested RISC-V, LM32, OpenRisc successfully), but the format returned by `readelf` seems a bit different on 64-bit and the script does not parse the data correctly:

````
  File "litex/litex/litex/soc/software/memusage.py", line 32, in print_usage
    rom_usage += int(tokens[6], 16)
IndexError: list index out of range
````

Here is the returned format with a 32-bit toolchain:
````
lxsim --cpu-type=vexriscv
[...]
riscv32-unknown-linux-gnu-readelf -e soc_simsoc_litex_sim/software/bios/bios.elf
[...]
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .text             PROGBITS        00000000 000074 0025b4 00 WAX  0   0  4
  [ 2] .rodata           PROGBITS        000025b4 002628 001134 00   A  0   0  4
  [ 3] .data             PROGBITS        000036e8 00375c 000000 00  WA  0   0  1
  [ 4] .bss              NOBITS          01000000 00375c 000130 00  WA  0   0  4
  [ 5] .debug_line       PROGBITS        00000000 00375c 005f11 00      0   0  1
  [ 6] .debug_info       PROGBITS        00000000 00966d 004bc3 00      0   0  1
  [ 7] .debug_abbrev     PROGBITS        00000000 00e230 0014d1 00      0   0  1
  [ 8] .debug_aranges    PROGBITS        00000000 00f708 0001e0 00      0   0  8
  [ 9] .debug_str        PROGBITS        00000000 00f8e8 004ce6 01  MS  0   0  1
  [10] .debug_loc        PROGBITS        00000000 0145ce 003452 00      0   0  1
  [11] .debug_macro      PROGBITS        00000000 017a20 001b12 00      0   0  1
  [12] .debug_ranges     PROGBITS        00000000 019532 0006f0 00      0   0  1
  [13] .symtab           SYMTAB          00000000 019c24 000810 10     14  51  4
  [14] .strtab           STRTAB          00000000 01a434 0003f4 00      0   0  1
  [15] .shstrtab         STRTAB          00000000 01a828 00009a 00      0   0  1
````

And with a 64-bit toolchain:
````
lxsim --cpu-type=rocket
[...]
riscv64-unknown-elf-readelf -e soc_simsoc_litex_sim/software/bios/bios.elf
[...]
Section Headers:
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .text             PROGBITS         0000000010000000  000000b0
       0000000000001e76  0000000000000000 WAX       0     0     2
  [ 2] .rodata           PROGBITS         0000000010001e78  00001f28
       00000000000012f0  0000000000000000   A       0     0     8
  [ 3] .srodata.cst8     PROGBITS         0000000010003168  00003218
       0000000000000008  0000000000000008  AM       0     0     8
  [ 4] .data             PROGBITS         0000000010003170  00003220
       0000000000000000  0000000000000000  WA       0     0     1
  [ 5] .bss              NOBITS           0000000011000000  00003220
       0000000000000148  0000000000000000  WA       0     0     8
  [ 6] .debug_line       PROGBITS         0000000000000000  00003220
       00000000000060fc  0000000000000000           0     0     1
  [ 7] .debug_info       PROGBITS         0000000000000000  0000931c
       0000000000005788  0000000000000000           0     0     1
  [ 8] .debug_abbrev     PROGBITS         0000000000000000  0000eaa4
       00000000000014e3  0000000000000000           0     0     1
  [ 9] .debug_aranges    PROGBITS         0000000000000000  0000ff90
       00000000000002d0  0000000000000000           0     0     16
  [10] .debug_str        PROGBITS         0000000000000000  00010260
       0000000000004dd4  0000000000000001  MS       0     0     1
  [11] .debug_loc        PROGBITS         0000000000000000  00015034
       00000000000058fb  0000000000000000           0     0     1
  [12] .debug_macro      PROGBITS         0000000000000000  0001a92f
       0000000000001b95  0000000000000000           0     0     1
  [13] .debug_ranges     PROGBITS         0000000000000000  0001c4c4
       0000000000000d10  0000000000000000           0     0     1
  [14] .symtab           SYMTAB           0000000000000000  0001d1d8
       0000000000000c48  0000000000000018          15    53     8
  [15] .strtab           STRTAB           0000000000000000  0001de20
       00000000000003f8  0000000000000000           0     0     1
  [16] .shstrtab         STRTAB           0000000000000000  0001e218
       00000000000000a8  0000000000000000           0     0     1
````
The results seem splitted on 2 lines with the 64-bit toolchain.

**Comment by enjoy-digital** [comment]
@fjullien: using `[readelf, '-e', '-W', bios]` to avoid the new line after the 80 characters makes it work.

**Comment by fjullien** [comment]
@enjoy-digital : thanks, PR updated

**Comment by enjoy-digital** [comment]
Thanks, merged.

**Pull request merged**
