### PR TITLE
Fixed Automatic programming of Altera DE10-nano board with Quartus 20…

### PR DESCRIPTION
**Pull request by Godtec**
….1.1 Dev tools.

Change line 14 of programmer.py file.
Add: def __init__(self, cable_name="DE-SoC", device_id=2):

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @Godtec, do you think it's was also broken for older version of Quartus or is it related to a change in Quartus?

**Comment by Godtec** [comment]
Don;t know. Didn't check, The only other version I have installed is Quartus tools 15.1. Did you want me to check there?

**Comment by enjoy-digital** [comment]
@Godtec yes that would be useful if it's not too complicated, I just want to understand if it's a change in Quartus (so if this PR will break support for older version and we should try to handle it) or if it was already broken and then this PR fixes the issue.

**Comment by Godtec** [comment]
@enjoy-digital: So I just checked Quartus 15.1. Seems to work fine with my change. It seems to be board related (As far as I can tell). I just complied for the DE10-Nano. I also have the de1-SoC Board, and the DE0-Nano-SoC. But not sure if you have support for the DE0 board. Also, I am currently working on adding support for the De1-SoC Board, completing the pin-out's and such. It has on board FPGA ram. Where the DE10-Nano, does not. Has some questions of the VGA part. Will try to message you directly if that's ok. Thanks! Programming Code attached:

make: Leaving directory '/home/mikek/Documents/Cyclone5_SOC/Litex_directory/linux-on-litex-vexriscv/build/de10nano/software/bios'
Info: *******************************************************************
Info: Running Quartus Prime Programmer
    Info: Version 15.1.0 Build 185 10/21/2015 SJ Lite Edition
    Info: Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
    Info: Your use of Altera Corporation's design tools, logic functions 
    Info: and other software and tools, and its AMPP partner logic 
    Info: functions, and any output files from any of the foregoing 
    Info: (including device programming or simulation files), and any 
    Info: associated documentation or information are expressly subject 
    Info: to the terms and conditions of the Altera Program License 
    Info: Subscription Agreement, the Altera Quartus Prime License Agreement,
    Info: the Altera MegaCore Function License Agreement, or other 
    Info: applicable license agreement, including, without limitation, 
    Info: that your use is for the sole purpose of programming logic 
    Info: devices manufactured by Altera and sold by Altera or its 
    Info: authorized distributors.  Please refer to the applicable 
    Info: agreement for further details.
    Info: Processing started: Wed Feb 10 14:33:14 2021
Info: Command: quartus_pgm -m jtag -c DE-SoC -o p;/home/mikek/Documents/Cyclone5_SOC/Litex_directory/linux-on-litex-vexriscv/build/de10nano/gateware/de10nano.sof@2
Info (213045): Using programming cable "DE-SoC [1-4]"
Info (213011): Using programming file /home/mikek/Documents/Cyclone5_SOC/Litex_directory/linux-on-litex-vexriscv/build/de10nano/gateware/de10nano.sof with checksum 0x05D39619 for device 5CSEBA6U23@2
Info (209060): Started Programmer operation at Wed Feb 10 14:33:15 2021
Info (209016): Configuring device index 2
Info (209017): Device 2 contains JTAG ID code 0x02D020DD
Info (209007): Configuration succeeded -- 1 device(s) configured
Info (209011): Successfully performed operation(s)
Info (209061): Ended Programmer operation at Wed Feb 10 14:33:17 2021
Info: Quartus Prime Programmer was successful. 0 errors, 0 warnings
    Info: Peak virtual memory: 397 megabytes
    Info: Processing ended: Wed Feb 10 14:33:17 2021
    Info: Elapsed time: 00:00:03
    Info: Total CPU time (on all processors): 00:00:01

**Comment by enjoy-digital** [comment]
Thanks @Godtec, the changes have been integrated in https://github.com/litex-hub/litex-boards/commit/9baa9d5d830a77c3f6bd952251c6cdeff72f69b4.

**Pull request closed without merging**
